"""NexusFile AI - Word Document Generator"""
import os
from docx import Document
from docx.shared import Inches, Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml
from config import GENERATED_FOLDER


# --- Colors ---
PRIMARY = RGBColor(0x6C, 0x5C, 0xE7)
SECONDARY = RGBColor(0x00, 0xCE, 0xC9)
DARK = RGBColor(0x2D, 0x3A, 0x4A)
TEXT_COLOR = RGBColor(0x2D, 0x34, 0x36)
SUBTEXT = RGBColor(0x63, 0x6E, 0x72)


def _style_table(table):
    """Apply professional styling to a table."""
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    # Style header row
    for cell in table.rows[0].cells:
        shading = parse_xml(f'<w:shd {nsdecls("w")} w:fill="6C5CE7"/>')
        cell._element.get_or_add_tcPr().append(shading)
        for paragraph in cell.paragraphs:
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            for run in paragraph.runs:
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.font.bold = True
                run.font.size = Pt(10)

    # Style data rows
    for row_idx, row in enumerate(table.rows[1:], 1):
        for cell in row.cells:
            if row_idx % 2 == 0:
                shading = parse_xml(f'<w:shd {nsdecls("w")} w:fill="F8F9FA"/>')
                cell._element.get_or_add_tcPr().append(shading)
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(10)
                    run.font.color.rgb = TEXT_COLOR

    # Set borders
    tbl = table._tbl
    tblPr = tbl.tblPr if tbl.tblPr is not None else parse_xml(f'<w:tblPr {nsdecls("w")}/>')
    borders = parse_xml(
        f'<w:tblBorders {nsdecls("w")}>'
        '  <w:top w:val="single" w:sz="4" w:space="0" w:color="DFE6E9"/>'
        '  <w:left w:val="single" w:sz="4" w:space="0" w:color="DFE6E9"/>'
        '  <w:bottom w:val="single" w:sz="4" w:space="0" w:color="DFE6E9"/>'
        '  <w:right w:val="single" w:sz="4" w:space="0" w:color="DFE6E9"/>'
        '  <w:insideH w:val="single" w:sz="4" w:space="0" w:color="DFE6E9"/>'
        '  <w:insideV w:val="single" w:sz="4" w:space="0" w:color="DFE6E9"/>'
        '</w:tblBorders>'
    )
    tblPr.append(borders)


def generate_docx(data: dict, filename: str) -> str:
    """Generate a styled Word document from structured data.

    Args:
        data: dict with 'title', 'subtitle', 'sections'
        filename: output filename (without extension)

    Returns:
        Full path to the generated .docx file
    """
    doc = Document()

    # --- Page margins ---
    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

    # --- Default font ---
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)
    font.color.rgb = TEXT_COLOR

    # ===== TITLE PAGE =====
    # Add some spacing
    for _ in range(4):
        doc.add_paragraph("")

    # Title
    title_text = data.get("title", "Document")
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_para.add_run(title_text)
    title_run.font.size = Pt(32)
    title_run.font.color.rgb = PRIMARY
    title_run.font.bold = True

    # Decorative line
    line_para = doc.add_paragraph()
    line_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    line_run = line_para.add_run("━" * 40)
    line_run.font.color.rgb = SECONDARY
    line_run.font.size = Pt(10)

    # Subtitle
    subtitle = data.get("subtitle", "")
    if subtitle:
        sub_para = doc.add_paragraph()
        sub_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub_run = sub_para.add_run(subtitle)
        sub_run.font.size = Pt(14)
        sub_run.font.color.rgb = SUBTEXT

    # Footer on title page
    for _ in range(6):
        doc.add_paragraph("")

    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer_para.add_run("Generated by NexusFile AI")
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = SUBTEXT
    footer_run.italic = True

    # Page break
    doc.add_page_break()

    # ===== CONTENT SECTIONS =====
    sections = data.get("sections", [])
    for section_data in sections:
        heading_text = section_data.get("heading", "Section")
        level = section_data.get("level", 1)
        level = min(max(level, 1), 3)

        # Add heading
        heading = doc.add_heading(heading_text, level=level)
        for run in heading.runs:
            run.font.color.rgb = PRIMARY if level == 1 else DARK

        # Content items
        content_items = section_data.get("content", [])
        for item in content_items:
            if isinstance(item, str):
                # Simple paragraph
                p = doc.add_paragraph(item)
                p.paragraph_format.space_after = Pt(8)
                continue

            if not isinstance(item, dict):
                continue

            item_type = item.get("type", "paragraph")

            if item_type == "paragraph":
                text = item.get("text", "")
                if isinstance(text, list):
                    text = "\n".join(text)
                p = doc.add_paragraph(text)
                p.paragraph_format.space_after = Pt(8)

            elif item_type == "bullet_list":
                items_list = item.get("text", [])
                if isinstance(items_list, str):
                    items_list = [items_list]
                for bullet in items_list:
                    p = doc.add_paragraph(bullet, style="List Bullet")
                    p.paragraph_format.space_after = Pt(4)

            elif item_type == "numbered_list":
                items_list = item.get("text", [])
                if isinstance(items_list, str):
                    items_list = [items_list]
                for num_item in items_list:
                    p = doc.add_paragraph(num_item, style="List Number")
                    p.paragraph_format.space_after = Pt(4)

            elif item_type == "table":
                headers = item.get("headers", [])
                rows = item.get("rows", [])
                if headers:
                    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
                    table.autofit = True

                    # Fill headers
                    for col_idx, header in enumerate(headers):
                        cell = table.rows[0].cells[col_idx]
                        cell.text = str(header)

                    # Fill data
                    for row_idx, row_data in enumerate(rows):
                        for col_idx, value in enumerate(row_data):
                            if col_idx < len(headers):
                                cell = table.rows[row_idx + 1].cells[col_idx]
                                cell.text = str(value)

                    _style_table(table)
                    doc.add_paragraph("")  # Spacer

    # ===== SAVE =====
    safe_filename = "".join(c if c.isalnum() or c in (' ', '-', '_') else '_' for c in filename)
    output_path = os.path.join(GENERATED_FOLDER, f"{safe_filename}.docx")
    doc.save(output_path)
    return output_path
