"""NexusFile AI - PDF Report Generator"""
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable
)
from config import GENERATED_FOLDER


# --- Color Palette ---
PRIMARY = HexColor("#6C5CE7")
SECONDARY = HexColor("#00CEC9")
DARK = HexColor("#2D3A4A")
TEXT_COLOR = HexColor("#2D3436")
LIGHT_BG = HexColor("#F8F9FA")
ACCENT = HexColor("#FD79A8")
BORDER = HexColor("#DFE6E9")


def _get_styles():
    """Create custom paragraph styles."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="CoverTitle",
        parent=styles["Title"],
        fontSize=36,
        leading=44,
        textColor=PRIMARY,
        alignment=TA_CENTER,
        spaceAfter=20,
        fontName="Helvetica-Bold",
    ))

    styles.add(ParagraphStyle(
        name="CoverSubtitle",
        parent=styles["Normal"],
        fontSize=14,
        leading=20,
        textColor=DARK,
        alignment=TA_CENTER,
        spaceAfter=12,
    ))

    styles.add(ParagraphStyle(
        name="SectionHeading",
        parent=styles["Heading1"],
        fontSize=20,
        leading=26,
        textColor=PRIMARY,
        spaceBefore=24,
        spaceAfter=12,
        fontName="Helvetica-Bold",
        borderPadding=(0, 0, 4, 0),
    ))

    styles.add(ParagraphStyle(
        name="BodyText2",
        parent=styles["Normal"],
        fontSize=11,
        leading=17,
        textColor=TEXT_COLOR,
        alignment=TA_JUSTIFY,
        spaceAfter=10,
        firstLineIndent=0,
    ))

    styles.add(ParagraphStyle(
        name="FooterStyle",
        parent=styles["Normal"],
        fontSize=8,
        textColor=HexColor("#B2BEC3"),
        alignment=TA_CENTER,
    ))

    return styles


def _header_footer(canvas, doc):
    """Draw header and footer on each page."""
    canvas.saveState()

    # Header line
    canvas.setStrokeColor(PRIMARY)
    canvas.setLineWidth(2)
    canvas.line(30, A4[1] - 40, A4[0] - 30, A4[1] - 40)

    # Header text
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(HexColor("#B2BEC3"))
    canvas.drawString(30, A4[1] - 35, "NexusFile AI Report")

    # Footer
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(HexColor("#B2BEC3"))
    canvas.drawCentredString(A4[0] / 2, 25, f"Page {doc.page}")

    # Footer line
    canvas.setStrokeColor(SECONDARY)
    canvas.setLineWidth(1)
    canvas.line(30, 40, A4[0] - 30, 40)

    canvas.restoreState()


def generate_pdf(data: dict, filename: str) -> str:
    """Generate a styled PDF report from structured data.

    Args:
        data: dict with 'title', 'author', 'date', 'sections'
        filename: output filename (without extension)

    Returns:
        Full path to the generated .pdf file
    """
    safe_filename = "".join(c if c.isalnum() or c in (' ', '-', '_') else '_' for c in filename)
    output_path = os.path.join(GENERATED_FOLDER, f"{safe_filename}.pdf")

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=60,
        bottomMargin=60,
        leftMargin=40,
        rightMargin=40,
    )

    styles = _get_styles()
    story = []

    # ===== COVER PAGE =====
    story.append(Spacer(1, 2 * inch))

    # Decorative top bar
    story.append(HRFlowable(
        width="80%", thickness=3, color=PRIMARY,
        spaceAfter=30, spaceBefore=0
    ))

    story.append(Paragraph(data.get("title", "Report"), styles["CoverTitle"]))

    story.append(HRFlowable(
        width="40%", thickness=1, color=SECONDARY,
        spaceAfter=30
    ))

    author = data.get("author", "NexusFile AI")
    date_str = data.get("date", datetime.now().strftime("%B %d, %Y"))
    story.append(Paragraph(f"Prepared by: {author}", styles["CoverSubtitle"]))
    story.append(Paragraph(f"Date: {date_str}", styles["CoverSubtitle"]))
    story.append(Spacer(1, 1 * inch))
    story.append(Paragraph("Generated by NexusFile AI", styles["FooterStyle"]))

    story.append(PageBreak())

    # ===== TABLE OF CONTENTS =====
    sections = data.get("sections", [])
    story.append(Paragraph("Table of Contents", styles["SectionHeading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=16))

    for i, section in enumerate(sections, 1):
        heading = section.get("heading", f"Section {i}")
        toc_style = ParagraphStyle(
            name=f"TOC_{i}",
            parent=styles["Normal"],
            fontSize=12,
            leading=20,
            textColor=DARK,
            leftIndent=20,
        )
        story.append(Paragraph(f"{i}.  {heading}", toc_style))

    story.append(PageBreak())

    # ===== SECTIONS =====
    for i, section in enumerate(sections, 1):
        heading = section.get("heading", f"Section {i}")
        story.append(Paragraph(f"{i}. {heading}", styles["SectionHeading"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceAfter=12))

        # Paragraphs
        paragraphs = section.get("paragraphs", [])
        for para in paragraphs:
            story.append(Paragraph(para, styles["BodyText2"]))

        # Table (optional)
        table_data = section.get("table")
        if table_data and isinstance(table_data, dict):
            headers = table_data.get("headers", [])
            rows = table_data.get("rows", [])
            if headers:
                all_data = [headers] + rows
                table = Table(all_data, repeatRows=1)
                table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                    ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#FFFFFF")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 10),
                    ("FONTSIZE", (0, 1), (-1, -1), 9),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#FFFFFF"), LIGHT_BG]),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ]))
                story.append(Spacer(1, 10))
                story.append(table)
                story.append(Spacer(1, 10))

        story.append(Spacer(1, 12))

    # Build
    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return output_path
