"""NexusFile AI - PowerPoint Generator"""
import os
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from config import GENERATED_FOLDER


# --- Color Palette ---
COLORS = {
    "primary":    RGBColor(0x6C, 0x5C, 0xE7),  # Purple
    "secondary":  RGBColor(0x00, 0xCE, 0xC9),  # Teal
    "dark":       RGBColor(0x2D, 0x3A, 0x4A),  # Dark blue-gray
    "darker":     RGBColor(0x1A, 0x1A, 0x2E),  # Very dark
    "light":      RGBColor(0xFD, 0xFD, 0xFD),  # Near white
    "accent":     RGBColor(0xFD, 0x79, 0xA8),  # Pink accent
    "text":       RGBColor(0xFF, 0xFF, 0xFF),  # White
    "subtext":    RGBColor(0xB2, 0xBE, 0xC3),  # Gray
}


def _set_slide_bg(slide, color):
    """Set solid background color for a slide."""
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_shape_with_text(slide, left, top, width, height, text, font_size=18, bold=False, color=None, alignment=PP_ALIGN.LEFT):
    """Add a text box to a slide."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = Pt(font_size)
    p.font.bold = bold
    p.font.color.rgb = color or COLORS["text"]
    p.alignment = alignment
    return txBox


def _add_accent_bar(slide, left, top, width, height, color):
    """Add a colored rectangle accent bar."""
    shape = slide.shapes.add_shape(
        1,  # MSO_SHAPE.RECTANGLE
        left, top, width, height
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    shape.line.fill.background()
    return shape


def generate_ppt(data: dict, filename: str) -> str:
    """Generate a styled PowerPoint file from structured data.

    Args:
        data: dict with 'title', 'subtitle', 'slides' (list of slide dicts)
        filename: output filename (without extension)

    Returns:
        Full path to the generated .pptx file
    """
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    slide_width = prs.slide_width
    slide_height = prs.slide_height

    # ===== TITLE SLIDE =====
    slide_layout = prs.slide_layouts[6]  # Blank
    slide = prs.slides.add_slide(slide_layout)
    _set_slide_bg(slide, COLORS["darker"])

    # Left accent bar
    _add_accent_bar(slide, Inches(0), Inches(0), Inches(0.15), slide_height, COLORS["primary"])

    # Top decorative bar
    _add_accent_bar(slide, Inches(0), Inches(0), slide_width, Inches(0.06), COLORS["secondary"])

    # Title
    _add_shape_with_text(
        slide, Inches(1.5), Inches(2.2), Inches(10), Inches(1.5),
        data.get("title", "Presentation"), font_size=44, bold=True,
        color=COLORS["text"], alignment=PP_ALIGN.LEFT
    )

    # Subtitle
    _add_shape_with_text(
        slide, Inches(1.5), Inches(3.8), Inches(8), Inches(1),
        data.get("subtitle", ""), font_size=20,
        color=COLORS["subtext"], alignment=PP_ALIGN.LEFT
    )

    # Bottom accent
    _add_accent_bar(
        slide, Inches(1.5), Inches(5.5), Inches(3), Inches(0.06),
        COLORS["accent"]
    )

    # "Generated by NexusFile AI"
    _add_shape_with_text(
        slide, Inches(1.5), Inches(6.2), Inches(5), Inches(0.5),
        "Generated by NexusFile AI", font_size=12,
        color=COLORS["subtext"], alignment=PP_ALIGN.LEFT
    )

    # ===== CONTENT SLIDES =====
    slides_data = data.get("slides", [])
    for i, s in enumerate(slides_data):
        slide = prs.slides.add_slide(slide_layout)
        _set_slide_bg(slide, COLORS["darker"])

        # Left accent bar
        _add_accent_bar(slide, Inches(0), Inches(0), Inches(0.15), slide_height, COLORS["primary"])

        # Slide number
        _add_shape_with_text(
            slide, Inches(12), Inches(6.8), Inches(1), Inches(0.5),
            f"{i + 1}/{len(slides_data)}", font_size=11,
            color=COLORS["subtext"], alignment=PP_ALIGN.RIGHT
        )

        # Title bar area
        _add_accent_bar(slide, Inches(0.15), Inches(0), slide_width, Inches(1.4), COLORS["dark"])

        # Slide title
        _add_shape_with_text(
            slide, Inches(1), Inches(0.3), Inches(11), Inches(0.9),
            s.get("title", f"Slide {i + 1}"), font_size=30, bold=True,
            color=COLORS["text"], alignment=PP_ALIGN.LEFT
        )

        # Content bullets
        content = s.get("content", [])
        if content:
            txBox = slide.shapes.add_textbox(Inches(1.2), Inches(2.0), Inches(10.5), Inches(4.5))
            tf = txBox.text_frame
            tf.word_wrap = True

            for j, bullet in enumerate(content):
                if j == 0:
                    p = tf.paragraphs[0]
                else:
                    p = tf.add_paragraph()
                p.text = f"▸  {bullet}"
                p.font.size = Pt(18)
                p.font.color.rgb = COLORS["light"]
                p.space_after = Pt(14)
                p.line_spacing = Pt(28)

        # Decorative bottom bar
        _add_accent_bar(
            slide, Inches(0.15), Inches(7.3), slide_width, Inches(0.06),
            COLORS["secondary"]
        )

    # ===== SAVE =====
    safe_filename = "".join(c if c.isalnum() or c in (' ', '-', '_') else '_' for c in filename)
    output_path = os.path.join(GENERATED_FOLDER, f"{safe_filename}.pptx")
    prs.save(output_path)
    return output_path
